//
//  Linear+WithClaude.swift
//  MUTE
//  NOTE: This codebase is generated by Claude (Fable 5)
//  Globally optimal positive power fitting via Riesz–Fejér Gram lifting.
//

import protocol Accelerate.AccelerateBuffer
import typealias Accelerate.vDSP
import typealias Accelerate.vForce
import BLAS
import LAPACK

extension Linear {
    /// Alternative power fitter kept in a namespace so it can coexist with
    /// `Linear.fit(xx:yy:frequency:weight:iteration:minimum:count:)`.
    public enum WithClaude {}
}

extension Linear.WithClaude {
    /// Fits `P(cos 2πω) Sxx - Q(cos 2πω) Syy = 0` with `P, Q >= minimum` on
    /// the whole interval, to global optimality.
    ///
    /// Because the Chebyshev argument is `cos 2πω`, interval nonnegativity is
    /// circle nonnegativity of an even trigonometric polynomial, so
    /// Riesz–Fejér applies exactly: `P - ε = ψᴴ G ψ` with one PSD Gram matrix
    /// `G` per polynomial and the linear map `p₀ = ε + tr G`,
    /// `p_k = 2 Σᵢ G[i, i+k]`. The semi-infinite constraint becomes two small
    /// PSD cones — no grid constraints, no cutting planes, no barrier bias —
    /// and the whole problem is a convex semidefinite least squares whose
    /// solution is the global optimum of the original fit.
    ///
    /// The cone program is solved by ADMM: the quadratic step reuses one
    /// cached `posv` inverse (plus a Schur correction for `p₀ + q₀ = 2`), and
    /// the cone step projects each Gram block through `gesvd` using the polar
    /// identity `Π(S) = (S + V Σ Vᵀ) / 2` for symmetric `S`.
    public static func fit(xx x: some AccelerateBuffer<Float64>,
                           yy y: some AccelerateBuffer<Float64>,
                           frequency ω: some AccelerateBuffer<Float64>, // normalized angular frequency, [0, 0.5] a.k.a. [0, π] or [0, 1) a.k.a. [0, 2π)
                           weight w: some AccelerateBuffer<Float64>, // weight factor for each frequency ω
                           iteration: Optional<Int> = .none,
                           minimum ε: Float64,
                           count: (p: Int, q: Int)) -> Linear.Direct.Power {
        let m = ω.count
        precondition(0 < m)
        precondition(m == x.count)
        precondition(m == y.count)
        precondition(m == w.count)
        precondition(0 <= count.p)
        precondition(0 <= count.q)
        precondition(ε.isFinite && 0 < ε && ε < 1)
        precondition(x.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        precondition(y.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        precondition(ω.withUnsafeBufferPointer { $0.allSatisfy(\.isFinite) })
        precondition(w.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        let p = count.p + 1
        let q = count.q + 1
        let small = p + q
        let root2 = 2.0.squareRoot()
        let xx = x.withUnsafeBufferPointer(Array.init)
        let yy = y.withUnsafeBufferPointer(Array.init)
        let ww = w.withUnsafeBufferPointer(Array.init)
        let ff = ω.withUnsafeBufferPointer(Array.init)
        // Weighted data columns: base[l] = sqrt(w/(x² + y²)) (x, -y).
        var xcol = Array<Float64>(repeating: 0, count: m)
        var ycol = Array<Float64>(repeating: 0, count: m)
        for l in 0..<m {
            let h = (xx[l] * xx[l] + yy[l] * yy[l]).squareRoot()
            let s = ww[l].squareRoot()
            if 0 < h, h.isFinite, 0 < s {
                xcol[l] = s * xx[l] / h
                ycol[l] = -s * yy[l] / h
            }
        }
        // M[:, k] = xcol T_k, M[:, p + k] = ycol T_k; T_k(cos 2πω) = cos 2πkω.
        var M = Array<Float64>(repeating: 0, count: m * small)
        M.replaceSubrange(0..<m, with: xcol)
        M.replaceSubrange(p * m ..< p * m + m, with: ycol)
        if 1 < max(p, q) {
            var t = Array<Float64>(repeating: 0, count: m)
            for k in 1..<max(p, q) {
                vDSP.multiply(2 * Float64(k), ff, result: &t)
                vForce.cosPi(t, result: &t)
                if k < p {
                    vDSP.multiply(t, xcol, result: &M[k * m ..< k * m + m])
                }
                if k < q {
                    vDSP.multiply(t, ycol, result: &M[(p + k) * m ..< (p + k) * m + m])
                }
            }
        }
        // Small data Gram; every lifted column is a scaled copy of a column
        // of M, so the big quadratic expands from Γ without materializing it.
        var Γ = Array<Float64>(repeating: 0, count: small * small)
        gemm(small, small, m, 1, M, m, .T, M, m, .N, 0, &Γ, small)
        // Scaled svec layout (‖svec‖₂ = ‖G‖_F): per block, columns j, rows
        // i <= j; the entry feeds Chebyshev coefficient k = j - i of its
        // polynomial with factor 1 on the diagonal and √2 off it.
        let nP = p * (p + 1) / 2
        let nQ = q * (q + 1) / 2
        let N = nP + nQ
        var κ = Array<Int>()     // column of M the svec entry couples to
        var factor = Array<Float64>()
        var diagonal = Array<Bool>()
        κ.reserveCapacity(N)
        factor.reserveCapacity(N)
        diagonal.reserveCapacity(N)
        for (base, d) in [(0, p), (p, q)] {
            for j in 0..<d {
                for i in 0...j {
                    κ.append(base + j - i)
                    factor.append(i == j ? 1 : root2)
                    diagonal.append(i == j)
                }
            }
        }
        // K = 2 ÂᵀÂ + ρI, inverted once; Â = M L with L the svec→coefficient map.
        var K = Array<Float64>(repeating: 0, count: N * N)
        for c2 in 0..<N {
            for c1 in 0..<N {
                K[c1 + c2 * N] = 2 * factor[c1] * factor[c2] * Γ[κ[c1] + κ[c2] * small]
            }
        }
        var trace = 0.0
        for c in 0..<N {
            trace += K[c + c * N]
        }
        let ρ = max(trace / Float64(N), 1)
        for c in 0..<N {
            K[c + c * N] += ρ
        }
        var Kinv = Array<Float64>(repeating: 0, count: N * N)
        for c in 0..<N {
            Kinv[c + c * N] = 1
        }
        switch posv(N, N, &K, N, .L, &Kinv, N) {
        case let info:
            precondition(info == 0)
        }
        // Linear term of ‖Âu + b‖²: b = ε (M[:,0] + M[:,p]) from the constant
        // Chebyshev coefficients of both polynomials.
        var g = Array<Float64>(repeating: 0, count: N)
        for c in 0..<N {
            g[c] = ε * factor[c] * (Γ[κ[c] + 0 * small] + Γ[κ[c] + p * small])
        }
        // Equality p₀ + q₀ = 2 ⟺ tr G + tr H = 2 - 2ε, handled by a Schur
        // correction against the cached inverse.
        let β = 2 - 2 * ε
        var a = Array<Float64>(repeating: 0, count: N)
        for c in 0..<N where diagonal[c] {
            a[c] = 1
        }
        var kA = Array<Float64>(repeating: 0, count: N)
        gemv(N, N, 1, Kinv, N, .N, a, 1, 0, &kA, 1)
        let aKa = dot(N, a, 1, kA, 1)
        precondition(0 < aKa)
        // PSD projection scratch (gesvd of symmetric block, polar identity).
        let dmax = max(p, q)
        let lwork = gesvd(dmax, dmax,
                          .none, dmax,
                          .none,
                          .none, dmax,
                          .init(bitPattern: ~0), dmax,
                          .none as Optional<UnsafeMutablePointer<Float64>>, 0)
        assert(0 < lwork)
        var S0 = Array<Float64>(repeating: 0, count: dmax * dmax)
        var SV = S0
        var VT = S0
        var SW = S0
        var Π = S0
        var σ = Array<Float64>(repeating: 0, count: dmax)
        var work = Array<Float64>(repeating: 0, count: lwork)
        func project(_ s: inout Array<Float64>, offset: Int, d: Int) {
            var c = offset
            for j in 0..<d {
                for i in 0...j {
                    let value = i == j ? s[c] : s[c] / root2
                    S0[i + j * d] = value
                    S0[j + i * d] = value
                    c += 1
                }
            }
            SV = S0
            switch gesvd(d, d, &SV, d, &σ, .none, d, &VT, d, &work, lwork) {
            case let info:
                assert(info == 0)
            }
            for j in 0..<d { // SW = diag(σ) VT
                for i in 0..<d {
                    SW[i + j * d] = σ[i] * VT[i + j * d]
                }
            }
            gemm(d, d, d, 0.5, VT, d, .T, SW, d, .N, 0, &Π, d) // polar/2
            c = offset
            for j in 0..<d { // Π(S) = (S + VᵀΣV)/2 back onto scaled svec
                for i in 0...j {
                    let value = 0.5 * S0[i + j * d] + Π[i + j * d]
                    s[c] = i == j ? value : value * root2
                    c += 1
                }
            }
        }
        // Strictly feasible start: P = Q = 1 (uniform diagonal Grams).
        var z = Array<Float64>(repeating: 0, count: N)
        for c in 0..<N where diagonal[c] {
            z[c] = (1 - ε) / Float64(c < nP ? p : q)
        }
        var u = z
        var v = Array<Float64>(repeating: 0, count: N)
        var rhs = v
        var zz = z
        let tolerance = 1e-10 * Float64(N).squareRoot()
        for _ in 0..<max(64, iteration ?? 4096) {
            // u = argmin uᵀK₀u + 2gᵀu + (ρ/2)‖u - z + v‖² s.t. aᵀu = β
            for c in 0..<N {
                rhs[c] = ρ * (z[c] - v[c]) - 2 * g[c]
            }
            gemv(N, N, 1, Kinv, N, .N, rhs, 1, 0, &u, 1)
            let μ = (dot(N, a, 1, u, 1) - β) / aKa
            for c in 0..<N {
                u[c] -= μ * kA[c]
            }
            // z = Π_PSD(u + v) per Gram block
            swap(&z, &zz)
            for c in 0..<N {
                z[c] = u[c] + v[c]
            }
            project(&z, offset: 0, d: p)
            project(&z, offset: nP, d: q)
            // v += u - z, residuals
            var primal = 0.0
            var dual = 0.0
            var scale = 0.0
            for c in 0..<N {
                let r = u[c] - z[c]
                let s = z[c] - zz[c]
                v[c] += r
                primal += r * r
                dual += s * s
                scale = max(scale, abs(z[c]))
            }
            if primal.squareRoot() <= tolerance * (1 + scale),
               ρ * dual.squareRoot() <= tolerance * (1 + scale) * ρ {
                break
            }
        }
        // Coefficients from the projected (hence certified PSD) iterate; the
        // common rescale restores p₀ + q₀ = 2 exactly without changing P/Q.
        var coefficients = Array<Float64>(repeating: 0, count: small)
        coefficients[0] = ε
        coefficients[p] = ε
        for c in 0..<N {
            coefficients[κ[c]] += factor[c] * z[c]
        }
        let scale = 2 / (coefficients[0] + coefficients[p])
        vDSP.multiply(scale, coefficients, result: &coefficients)
        return .init(raw: (Array(coefficients.prefix(p)),
                           Array(coefficients.suffix(q))))
    }
}
