//
//  Linear+WithCodex.swift
//  MUTE
//  NOTE: This codebase is generated by Codex (GPT-5.6 Sol Medium)
//  Dense-grid, strictly-feasible barrier solver for positive power fitting.
//

import protocol Accelerate.AccelerateBuffer
import typealias Accelerate.vDSP
import typealias Accelerate.vForce
import BLAS
import LAPACK
import func Darwin.log

extension Linear {
    /// Alternative power fitter kept in a namespace so it can coexist with
    /// `Linear.fit(xx:yy:frequency:weight:iteration:minimum:count:)`.
    public enum WithCodex {}
}

extension Linear.WithCodex {
    /// Fits `P(cos(2πω)) Sxx - Q(cos(2πω)) Syy = 0` while constraining
    /// `P,Q >= minimum` on the complete supplied frequency grid.
    ///
    /// The scale constraint `p[0] + q[0] = 2` is eliminated exactly.  The
    /// remaining strictly feasible QP is solved with a logarithmic barrier
    /// and damped Newton steps.  Continuous-interval minima are then used as
    /// cutting planes; root finding is not part of the main optimization.
    public static func fit(xx x: some AccelerateBuffer<Float64>,
                           yy y: some AccelerateBuffer<Float64>,
                           frequency omega: some AccelerateBuffer<Float64>,
                           weight: some AccelerateBuffer<Float64>,
                           iteration: Optional<Int> = .none,
                           minimum epsilon: Float64,
                           count: (p: Int, q: Int)) -> Linear.Direct.Power {
        let sampleCount = omega.count
        precondition(0 < sampleCount)
        precondition(sampleCount == x.count)
        precondition(sampleCount == y.count)
        precondition(sampleCount == weight.count)
        precondition(0 <= count.p && 0 <= count.q)
        precondition(epsilon.isFinite && 0 < epsilon && epsilon < 1)
        precondition(x.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        precondition(y.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        precondition(omega.withUnsafeBufferPointer { $0.allSatisfy(\.isFinite) })
        precondition(weight.withUnsafeBufferPointer {
            $0.allSatisfy { $0.isFinite && 0 <= $0 }
        })

        let pCount = count.p + 1
        let qCount = count.q + 1
        let variableCount = pCount + qCount - 1
        precondition(variableCount <= sampleCount)

        let frequencies = omega.withUnsafeBufferPointer(Array.init)
        let xx = x.withUnsafeBufferPointer(Array.init)
        let yy = y.withUnsafeBufferPointer(Array.init)
        let weights = weight.withUnsafeBufferPointer(Array.init)
        let inverseSquareRootOfTwo = 1.0 / 2.0.squareRoot()

        // A small optimization margin prevents a point whose true value is
        // epsilon from being classified as infeasible solely by round-off.
        let requestedMargin = max(1.0e-10,
                                  256 * Float64.ulpOfOne * Float64(max(pCount, qCount)))
        let gridMargin = min(requestedMargin, 0.01 * (1 - epsilon))
        let constrainedMinimum = epsilon + gridMargin

        // T is column-major: T[l + k * sampleCount] = T_k(cos(2*pi*omega[l])).
        let maximumCount = max(pCount, qCount)
        var chebyshev = Array(repeating: 0.0, count: sampleCount * maximumCount)
        vDSP.fill(&chebyshev[0..<sampleCount], with: 1)
        if 1 < maximumCount {
            var phase = Array(repeating: 0.0, count: sampleCount)
            for k in 1..<maximumCount {
                vDSP.multiply(2 * Float64(k), frequencies, result: &phase)
                vForce.cosPi(phase, result: &chebyshev[k * sampleCount..<(k + 1) * sampleCount])
            }
        }

        // Eliminate p0 + q0 = 2 with the orthonormal coordinate
        // u0 = (p0 - q0) / sqrt(2).  The remaining coordinates are
        // p1... and q1....  Hence p0 = 1 + u0/sqrt(2),
        // q0 = 1 - u0/sqrt(2).
        var design = Array(repeating: 0.0, count: sampleCount * variableCount)
        var offset = Array(repeating: 0.0, count: sampleCount)
        var sx = Array(repeating: 0.0, count: sampleCount)
        var sy = Array(repeating: 0.0, count: sampleCount)
        for l in 0..<sampleCount {
            let scale = weights[l].squareRoot()
            let maximum = max(xx[l], yy[l])
            let minimum = min(xx[l], yy[l])
            let ratio = 0 < maximum ? minimum / maximum : 0
            let denominator = maximum * (1 + ratio * ratio).squareRoot()
            if 0 < denominator && denominator.isFinite && 0 < scale {
                sx[l] = scale * xx[l] / denominator
                sy[l] = -scale * yy[l] / denominator
            }
            offset[l] = sx[l] + sy[l]
            design[l] = (sx[l] - sy[l]) * inverseSquareRootOfTwo
        }
        if 1 < pCount {
            for k in 1..<pCount {
                let column = k
                vDSP.multiply(sx,
                              chebyshev[k * sampleCount..<(k + 1) * sampleCount],
                              result: &design[column * sampleCount..<(column + 1) * sampleCount])
            }
        }
        if 1 < qCount {
            for k in 1..<qCount {
                let column = pCount - 1 + k
                vDSP.multiply(sy,
                              chebyshev[k * sampleCount..<(k + 1) * sampleCount],
                              result: &design[column * sampleCount..<(column + 1) * sampleCount])
            }
        }

        // Constant data Hessian and linear term of
        // 0.5 * ||design * u + offset||^2.
        var dataHessian = Array(repeating: 0.0, count: variableCount * variableCount)
        gemm(variableCount, variableCount, sampleCount,
             1,
             design, sampleCount, .T,
             design, sampleCount, .N,
             0,
             &dataHessian, variableCount)
        var linear = Array(repeating: 0.0, count: variableCount)
        gemv(sampleCount, variableCount,
             1,
             design, sampleCount, .T,
             offset, 1,
             0,
             &linear, 1)

        // Penalize high-order ripple.  A light ridge is retained on every
        // coordinate. Scaling lambda by the data Hessian makes the setting
        // invariant to a common scaling of all weights.
        var regularizer = Array(repeating: 0.0, count: variableCount)
        if 1 < pCount {
            for k in 1..<pCount {
                regularizer[k] = Float64(k * k * k * k)
            }
        }
        if 1 < qCount {
            for k in 1..<qCount {
                regularizer[pCount - 1 + k] = Float64(k * k * k * k)
            }
        }
        let hessianScale = max(1,
                               stride(from: 0,
                                      to: variableCount * variableCount,
                                      by: variableCount + 1).lazy
                                .map { dataHessian[$0] }
                                .reduce(0, +) / Float64(variableCount))
        let regularizationScale = 1.0e-12 * hessianScale
        for j in 0..<variableCount {
            dataHessian[j + j * variableCount] += regularizationScale * max(1, regularizer[j])
        }

        var pCuts = Array<Float64>()
        var qCuts = Array<Float64>()
        var solution = linear.map(-)
        var unconstrainedFactor = dataHessian
        let unconstrainedInfo = posv(variableCount, 1,
                                     &unconstrainedFactor, variableCount, .L,
                                     &solution, variableCount)
        if unconstrainedInfo != 0 || !solution.allSatisfy(\.isFinite) {
            solution = Array(repeating: 0.0, count: variableCount)
        } else {
            let unconstrained = Self.coefficients(solution: solution,
                                                  pCount: pCount,
                                                  qCount: qCount)
            if Self.minimum(of: unconstrained.p).value >= constrainedMinimum &&
                Self.minimum(of: unconstrained.q).value >= constrainedMinimum {
                return .init(raw: (unconstrained.p, unconstrained.q))
            }
        }
        let maximumNewtonIterationsPerStage = max(8, iteration ?? 32)

        // A polynomial of degrees p and q cannot require more than p + q
        // distinct interior minimum cuts.  The two extra rounds cover the
        // interval endpoints and numerical duplicates.
        for _ in 0..<(pCount + qCount + 2) {
            let constraintCount = 2 * sampleCount + pCuts.count + qCuts.count
            var constraints = Array(repeating: 0.0,
                                    count: constraintCount * variableCount)

            // G*u + (1 - constrainedMinimum) > 0.
            for l in 0..<sampleCount {
                constraints[l] = inverseSquareRootOfTwo
                constraints[sampleCount + l] = -inverseSquareRootOfTwo
            }
            if 1 < pCount {
                for k in 1..<pCount {
                    let sourceStart = k * sampleCount
                    let targetStart = k * constraintCount
                    for l in 0..<sampleCount {
                        constraints[targetStart + l] = chebyshev[sourceStart + l]
                    }
                }
            }
            if 1 < qCount {
                for k in 1..<qCount {
                    let column = pCount - 1 + k
                    let sourceStart = k * sampleCount
                    let targetStart = column * constraintCount + sampleCount
                    for l in 0..<sampleCount {
                        constraints[targetStart + l] = chebyshev[sourceStart + l]
                    }
                }
            }

            var row = 2 * sampleCount
            for location in pCuts {
                let basis = Array(Linear.Direct.ChebyshevPolynomial.basis(at: location).prefix(pCount))
                constraints[row] = inverseSquareRootOfTwo
                for k in 1..<pCount {
                    constraints[row + k * constraintCount] = basis[k]
                }
                row += 1
            }
            for location in qCuts {
                let basis = Array(Linear.Direct.ChebyshevPolynomial.basis(at: location).prefix(qCount))
                constraints[row] = -inverseSquareRootOfTwo
                for k in 1..<qCount {
                    constraints[row + (pCount - 1 + k) * constraintCount] = basis[k]
                }
                row += 1
            }

            // Keep the unconstrained solution (or the preceding cut solution)
            // when possible.  If a newly added cut makes it infeasible, move
            // it toward the known strict interior point P=Q=1 just far enough
            // to restore a useful interior margin.
            Self.moveToStrictInterior(constraints: constraints,
                                      constraintOffset: 1 - constrainedMinimum,
                                      variables: variableCount,
                                      constraintsCount: constraintCount,
                                      solution: &solution)
            Self.solveBarrier(offset: offset,
                              dataHessian: dataHessian,
                              linear: linear,
                              constraints: constraints,
                              constraintOffset: 1 - constrainedMinimum,
                              variables: variableCount,
                              constraintsCount: constraintCount,
                              maximumIterationPerStage: maximumNewtonIterationsPerStage,
                              solution: &solution)

            let coefficients = Self.coefficients(solution: solution,
                                                 pCount: pCount,
                                                 qCount: qCount)
            let pMinimum = Self.minimum(of: coefficients.p)
            let qMinimum = Self.minimum(of: coefficients.q)
            var addedCut = false
            if pMinimum.value < constrainedMinimum,
               !pCuts.contains(where: { ($0 - pMinimum.location).magnitude < 1.0e-10 }) {
                pCuts.append(pMinimum.location)
                addedCut = true
            }
            if qMinimum.value < constrainedMinimum,
               !qCuts.contains(where: { ($0 - qMinimum.location).magnitude < 1.0e-10 }) {
                qCuts.append(qMinimum.location)
                addedCut = true
            }
            if !addedCut {
                precondition(pMinimum.value >= epsilon && qMinimum.value >= epsilon,
                             "Power fit did not establish continuous positivity: P min \(pMinimum.value) at \(pMinimum.location), Q min \(qMinimum.value) at \(qMinimum.location), requested \(epsilon)")
                return .init(raw: (coefficients.p, coefficients.q))
            }
        }

        let coefficients = Self.coefficients(solution: solution,
                                             pCount: pCount,
                                             qCount: qCount)
        let pMinimum = Self.minimum(of: coefficients.p).value
        let qMinimum = Self.minimum(of: coefficients.q).value
        precondition(pMinimum >= epsilon && qMinimum >= epsilon,
                     "Power fit did not establish continuous positivity: P min \(pMinimum), Q min \(qMinimum), requested \(epsilon)")
        return .init(raw: (coefficients.p, coefficients.q))
    }
}

extension Linear.WithCodex {
    static func solveBarrier(offset: Array<Float64>,
                             dataHessian: Array<Float64>,
                             linear: Array<Float64>,
                             constraints: Array<Float64>,
                             constraintOffset: Float64,
                             variables: Int,
                             constraintsCount: Int,
                             maximumIterationPerStage: Int,
                             solution: inout Array<Float64>) {
        var residual = Array(repeating: constraintOffset, count: constraintsCount)
        var inverseResidual = Array(repeating: 0.0, count: constraintsCount)
        var scaledConstraints = Array(repeating: 0.0,
                                      count: constraintsCount * variables)
        var gradient = Array(repeating: 0.0, count: variables)
        var hessian = Array(repeating: 0.0, count: variables * variables)
        var direction = Array(repeating: 0.0, count: variables)
        var constraintDirection = Array(repeating: 0.0, count: constraintsCount)
        var trial = Array(repeating: 0.0, count: variables)

        let initialDataObjective = 0.5 * offset.lazy.map { $0 * $0 }.reduce(0, +)
        var barrier = max(1.0e-4,
                          initialDataObjective / Float64(max(1, constraintsCount)))
        let minimumBarrier = 1.0e-13 * max(1, initialDataObjective) /
            Float64(max(1, constraintsCount))

        // `maximumIterationPerStage` is deliberately not shared by all
        // barrier values.  Sharing one budget used to stop after only a few
        // reductions of mu and left a visible analytic-center common factor
        // in P and Q when thousands of grid constraints were present.
        while minimumBarrier < barrier {
            for _ in 0..<maximumIterationPerStage {
                for index in residual.indices { residual[index] = constraintOffset }
                gemv(constraintsCount, variables,
                     1,
                     constraints, constraintsCount, .N,
                     solution, 1,
                     1,
                     &residual, 1)
                precondition(residual.allSatisfy { 0 < $0 && $0.isFinite },
                             "Barrier iterate left the strictly feasible region")

                for i in 0..<constraintsCount {
                    inverseResidual[i] = 1 / residual[i]
                }

                gradient = linear
                gemv(variables, variables,
                     1,
                     dataHessian, variables, .N,
                     solution, 1,
                     1,
                     &gradient, 1)
                gemv(constraintsCount, variables,
                     -barrier,
                     constraints, constraintsCount, .T,
                     inverseResidual, 1,
                     1,
                     &gradient, 1)

                hessian = dataHessian
                var scale = inverseResidual
                vDSP.multiply(barrier.squareRoot(), scale, result: &scale)
                for column in 0..<variables {
                    vDSP.multiply(constraints[column * constraintsCount..<(column + 1) * constraintsCount],
                                  scale,
                                  result: &scaledConstraints[column * constraintsCount..<(column + 1) * constraintsCount])
                }
                gemm(variables, variables, constraintsCount,
                     1,
                     scaledConstraints, constraintsCount, .T,
                     scaledConstraints, constraintsCount, .N,
                     1,
                     &hessian, variables)

                direction = gradient.map(-)
                var factor = hessian
                var info = posv(variables, 1,
                                &factor, variables, .L,
                                &direction, variables)
                if info != 0 {
                    let loading = max(1.0e-14,
                                      1.0e-12 * stride(from: 0,
                                                       to: variables * variables,
                                                       by: variables + 1).lazy
                                        .map { hessian[$0].magnitude }
                                        .reduce(0, +) / Float64(variables))
                    factor = hessian
                    for j in 0..<variables {
                        factor[j + j * variables] += loading
                    }
                    direction = gradient.map(-)
                    info = posv(variables, 1,
                                &factor, variables, .L,
                                &direction, variables)
                }
                precondition(info == 0, "Newton system is numerically singular")

                let decrementSquared = max(0,
                                           -zip(gradient, direction).lazy
                                            .map(*).reduce(0, +))
                if decrementSquared <= 1.0e-12 * max(1, initialDataObjective) {
                    break
                }

                gemv(constraintsCount, variables,
                     1,
                     constraints, constraintsCount, .N,
                     direction, 1,
                     0,
                     &constraintDirection, 1)
                var step = 1.0
                for i in 0..<constraintsCount where constraintDirection[i] < 0 {
                    step = min(step, 0.995 * -residual[i] / constraintDirection[i])
                }

                let currentObjective = Self.barrierObjective(dataHessian: dataHessian,
                                                             linear: linear,
                                                             constraints: constraints,
                                                             constraintOffset: constraintOffset,
                                                             variables: variables,
                                                             constraintsCount: constraintsCount,
                                                             barrier: barrier,
                                                             solution: solution)
                let directionalDerivative = zip(gradient, direction).lazy.map(*).reduce(0, +)
                while 1.0e-12 < step {
                    for j in 0..<variables {
                        trial[j] = solution[j] + step * direction[j]
                    }
                    let candidate = Self.barrierObjective(dataHessian: dataHessian,
                                                          linear: linear,
                                                          constraints: constraints,
                                                          constraintOffset: constraintOffset,
                                                          variables: variables,
                                                          constraintsCount: constraintsCount,
                                                          barrier: barrier,
                                                          solution: trial)
                    if candidate.isFinite &&
                        candidate <= currentObjective + 1.0e-4 * step * directionalDerivative {
                        solution = trial
                        break
                    }
                    step *= 0.5
                }
                if step <= 1.0e-12 {
                    break
                }
            }
            barrier *= 0.1
        }
    }

    static func moveToStrictInterior(constraints: Array<Float64>,
                                     constraintOffset: Float64,
                                     variables: Int,
                                     constraintsCount: Int,
                                     solution: inout Array<Float64>) {
        guard solution.contains(where: { !$0.isZero }) else { return }
        var displacement = Array(repeating: 0.0, count: constraintsCount)
        gemv(constraintsCount, variables,
             1,
             constraints, constraintsCount, .N,
             solution, 1,
             0,
             &displacement, 1)
        var scale = 1.0
        let retainedMargin = 0.01 * constraintOffset
        for value in displacement where value < retainedMargin - constraintOffset {
            scale = min(scale, (constraintOffset - retainedMargin) / -value)
        }
        if scale < 1 {
            vDSP.multiply(max(0, 0.995 * scale), solution, result: &solution)
        }
    }

    static func barrierObjective(dataHessian: Array<Float64>,
                                 linear: Array<Float64>,
                                 constraints: Array<Float64>,
                                 constraintOffset: Float64,
                                 variables: Int,
                                 constraintsCount: Int,
                                 barrier: Float64,
                                 solution: Array<Float64>) -> Float64 {
        var quadratic = Array(repeating: 0.0, count: variables)
        gemv(variables, variables,
             1,
             dataHessian, variables, .N,
             solution, 1,
             0,
             &quadratic, 1)
        var value = zip(solution, quadratic).lazy.map(*).reduce(0, +) * 0.5
        value += zip(linear, solution).lazy.map(*).reduce(0, +)
        var residual = Array(repeating: constraintOffset, count: constraintsCount)
        gemv(constraintsCount, variables,
             1,
             constraints, constraintsCount, .N,
             solution, 1,
             1,
             &residual, 1)
        for item in residual {
            guard 0 < item && item.isFinite else { return .infinity }
            value -= barrier * log(item)
        }
        return value
    }

    static func coefficients(solution: Array<Float64>,
                             pCount: Int,
                             qCount: Int) -> (p: Array<Float64>, q: Array<Float64>) {
        let inverseSquareRootOfTwo = 1.0 / 2.0.squareRoot()
        var p = Array(repeating: 0.0, count: pCount)
        var q = Array(repeating: 0.0, count: qCount)
        p[0] = 1 + inverseSquareRootOfTwo * solution[0]
        q[0] = 1 - inverseSquareRootOfTwo * solution[0]
        if 1 < pCount {
            for k in 1..<pCount { p[k] = solution[k] }
        }
        if 1 < qCount {
            for k in 1..<qCount { q[k] = solution[pCount - 1 + k] }
        }
        return (p, q)
    }

    static func minimum(of coefficients: Array<Float64>) -> (value: Float64, location: Float64) {
        var trimmed = coefficients
        let scale = max(1, trimmed.lazy.map(\.magnitude).max() ?? 1)
        let tolerance = 512 * Float64.ulpOfOne * scale
        while 1 < trimmed.count && trimmed.last.unsafelyUnwrapped.magnitude <= tolerance {
            trimmed.removeLast()
        }
        return Linear.Direct.ChebyshevPolynomial(trimmed).minimum
    }
}
