//
//  Linear+WithClaude.swift
//  MUTE
//  NOTE: This codebase is generated by Claude (Fable 5)
//  Globally optimal positive power fitting via Riesz–Fejér Gram lifting.
//

import protocol Accelerate.AccelerateBuffer
import typealias Accelerate.vDSP
import typealias Accelerate.vForce
import BLAS
import LAPACK
import func Darwin.log

extension Linear {
    /// Alternative power fitter kept in a namespace so it can coexist with
    /// `Linear.fit(xx:yy:frequency:weight:iteration:minimum:count:)`.
    public enum WithClaude {}
}

extension Linear.WithClaude {
    /// Fits `P(cos 2πω) Sxx - Q(cos 2πω) Syy = 0` with `P, Q >= minimum` on
    /// the whole interval using a finite-accuracy convex barrier solve.
    ///
    /// Because the Chebyshev argument is `cos 2πω`, interval nonnegativity is
    /// circle nonnegativity of an even trigonometric polynomial, so
    /// Riesz–Fejér applies exactly: `P - ε = ψᴴ G ψ` with one PSD Gram matrix
    /// `G` per polynomial and the linear map `p₀ = ε + tr G`,
    /// `p_k = 2 Σᵢ G[i, i+k]`. The semi-infinite constraint becomes two small
    /// PSD cones — no grid constraints or cutting planes —
    /// and the whole problem is a convex semidefinite least squares whose
    /// barrier solutions approach the global optimum as μ tends to zero.
    /// `barrierFloor` is relative to the mean lifted data-Hessian diagonal.
    /// It controls analytic-center bias, not robustness to measurement noise.
    /// `iteration` bounds Newton steps per barrier stage, not total steps.
    ///
    /// The cone program is solved by a primal log-det barrier with damped
    /// Newton steps (`potrf`/`potrs`). Exact Newton steps are affine invariant;
    /// finite-precision factorization and emergency damping still limit LF
    /// accuracy. Backtracking checks both cone feasibility and Armijo descent.
    public static func fit(xx x: some AccelerateBuffer<Float64>,
                           yy y: some AccelerateBuffer<Float64>,
                           frequency ω: some AccelerateBuffer<Float64>, // normalized angular frequency, [0, 0.5] a.k.a. [0, π] or [0, 1) a.k.a. [0, 2π)
                           weight w: some AccelerateBuffer<Float64>, // weight factor for each frequency ω
                           iteration: Optional<Int> = .none,
                           barrierFloor: Float64 = 1e-14,
                           minimum ε: Float64,
                           count: (p: Int, q: Int)) -> Linear.Direct.Power {
        precondition(barrierFloor.isFinite && 0 < barrierFloor && barrierFloor <= 1)
        precondition(iteration == nil || iteration! > 0)
        let m = ω.count
        precondition(0 < m)
        precondition(m == x.count)
        precondition(m == y.count)
        precondition(m == w.count)
        precondition(0 <= count.p)
        precondition(0 <= count.q)
        precondition(ε.isFinite && 0 < ε && ε < 1)
        precondition(x.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        precondition(y.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        precondition(ω.withUnsafeBufferPointer { $0.allSatisfy(\.isFinite) })
        precondition(w.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        let p = count.p + 1
        let q = count.q + 1
        let small = p + q
        let root2 = 2.0.squareRoot()
        let xx = x.withUnsafeBufferPointer(Array.init)
        let yy = y.withUnsafeBufferPointer(Array.init)
        let ww = w.withUnsafeBufferPointer(Array.init)
        let ff = ω.withUnsafeBufferPointer(Array.init)
        // Weighted data columns: base[l] = sqrt(w/(x² + y²)) (x, -y).
        var xcol = Array<Float64>(repeating: 0, count: m)
        var ycol = Array<Float64>(repeating: 0, count: m)
        for (l, h) in vDSP.hypot(xx, yy).enumerated() {
            let s = ww[l].squareRoot()
            if 0 < h, h.isFinite, 0 < s {
                xcol[l] =  s * xx[l] / h
                ycol[l] = -s * yy[l] / h
            }
        }
        // M[:, k] = xcol T_k, M[:, p + k] = ycol T_k; T_k(cos 2πω) = cos 2πkω.
        var M = Array<Float64>(repeating: 0, count: m * small)
        M.replaceSubrange(0..<m, with: xcol)
        M.replaceSubrange(p * m ..< p * m + m, with: ycol)
        if 1 < max(p, q) {
            var t = Array<Float64>(repeating: 0, count: m)
            for k in 1..<max(p, q) {
                vDSP.multiply(2 * Float64(k), ff, result: &t)
                vForce.cosPi(t, result: &t)
                if k < p {
                    vDSP.multiply(t, xcol, result: &M[k * m ..< k * m + m])
                }
                if k < q {
                    vDSP.multiply(t, ycol, result: &M[(p + k) * m ..< (p + k) * m + m])
                }
            }
        }
        // Small data Gram; every lifted column is a scaled copy of a column
        // of M, so the big quadratic expands from Γ without materializing it.
        var Γ = Array<Float64>(repeating: 0, count: small * small)
        gemm(small, small, m, 1, M, m, .T, M, m, .N, 0, &Γ, small)
        // Scaled svec layout (‖svec‖₂ = ‖G‖_F): per block, columns j, rows
        // i <= j; the entry feeds Chebyshev coefficient k = j - i of its
        // polynomial with factor 1 on the diagonal and √2 off it.
        let nP = p * (p + 1) / 2
        let nQ = q * (q + 1) / 2
        let N = nP + nQ
        var κ = Array<Int>()     // column of M the svec entry couples to
        var factor = Array<Float64>()
        var diagonal = Array<Bool>()
        var row = Array<Int>()
        var col = Array<Int>()
        κ.reserveCapacity(N)
        factor.reserveCapacity(N)
        diagonal.reserveCapacity(N)
        row.reserveCapacity(N)
        col.reserveCapacity(N)
        for (base, d) in [(0, p), (p, q)] {
            for j in 0..<d {
                for i in 0...j {
                    κ.append(base + j - i)
                    factor.append(i == j ? 1 : root2)
                    diagonal.append(i == j)
                    row.append(i)
                    col.append(j)
                }
            }
        }
        // K₀ = ÂᵀÂ with Â = M L, L the svec→coefficient map; objective uᵀK₀u + 2gᵀu.
        var K = Array<Float64>(repeating: 0, count: N * N)
        for c2 in 0..<N {
            for c1 in 0..<N {
                K[c1 + c2 * N] = factor[c1] * factor[c2] * Γ[κ[c1] + κ[c2] * small]
            }
        }
        // Equality p₀ + q₀ = 2 ⟺ tr G + tr H = 2 - 2ε.
        let β = 2 - 2 * ε
        var a = Array<Float64>(repeating: 0, count: N)
        for c in 0..<N where diagonal[c] {
            a[c] = 1
        }
        // svec ↔ dense block helpers
        let dmax = max(p, q)
        var S = Array<Float64>(repeating: 0, count: dmax * dmax)
        var Wp = Array<Float64>(repeating: 0, count: p * p)
        var Wq = Array<Float64>(repeating: 0, count: q * q)
        func dense(_ u: borrowing Array<Float64>, _ offset: Int, _ d: Int) {
            var c = offset
            for j in 0..<d {
                for i in 0...j {
                    let value = i == j ? u[c] : u[c] / root2
                    S[i + j * d] = value
                    S[j + i * d] = value
                    c += 1
                }
            }
        }
        var trialCoefficients = Array<Float64>(repeating: 0, count: small)
        var trialResidual = Array<Float64>(repeating: 0, count: m)
        var dataGradient = Array<Float64>(repeating: 0, count: small)
        // Evaluate the data term from residuals rather than a cancellation-prone
        // expanded quadratic, especially near an exactly representable LF fit.
        func objective(_ u: borrowing Array<Float64>, _ μ: Float64) -> Float64? {
            var logDet = 0.0
            for (offset, d) in [(0, p), (nP, q)] {
                dense(u, offset, d)
                guard potrf(d, &S, d, .L) == 0 else { return nil }
                for i in 0..<d { logDet += 2 * log(S[i + i * d]) }
            }
            for i in 0..<small { trialCoefficients[i] = 0 }
            trialCoefficients[0] = ε
            trialCoefficients[p] = ε
            for c in 0..<N { trialCoefficients[κ[c]] += factor[c] * u[c] }
            gemv(m, small, 1, M, m, .N, trialCoefficients, 1, 0, &trialResidual, 1)
            let value = dot(m, trialResidual, 1, trialResidual, 1) - μ * logDet
            return value.isFinite ? value : nil
        }
        // W ← block⁻¹ via Cholesky; returns log det or nil when not PD
        func invert(_ u: borrowing Array<Float64>, _ offset: Int, _ d: Int, _ W: inout Array<Float64>) -> Bool {
            dense(u, offset, d)
            guard potrf(d, &S, d, .L) == 0 else { return false }
            W.withUnsafeMutableBufferPointer {
                vDSP.clear(&$0[...])
                for i in 0..<d {
                    $0[i + i * d] = 1
                }
            }
            switch potrs(d, d, &S, d, .L, &W, d) {
            case let info:
                assert(info == 0)
                return W.allSatisfy(\.isFinite) // marginal factors can overflow the inverse
            }
        }
        // Primal log-det barrier with damped Newton. Finite-precision
        // conditioning must still be checked with response-domain regressions.
        var u = Array<Float64>(repeating: 0, count: N)
        for c in 0..<N where diagonal[c] { // strictly feasible start: P = Q = 1
            u[c] = (1 - ε) / Float64(c < nP ? p : q)
        }
        var gradient = Array<Float64>(repeating: 0, count: N)
        var H = Array<Float64>(repeating: 0, count: N * N)
        var rhs = Array<Float64>(repeating: 0, count: 2 * N)
        var candidate = u
        let scaleK = (0..<N).reduce(0.0) { $0 + K[$1 + $1 * N] } / Float64(N)
        guard 0 < scaleK else {
            var cp = Array<Float64>(repeating: 0, count: p)
            var cq = Array<Float64>(repeating: 0, count: q)
            cp[0] = 1; cq[0] = 1
            return .init(raw: (cp, cq))
        }
        let μfloor = barrierFloor * scaleK
        var μ = scaleK
        while true {
            newton: for _ in 0..<(iteration ?? 64) {
                guard invert(u, 0, p, &Wp), invert(u, nP, q, &Wq) else {
                    break newton // numerically pinned to the cone boundary; keep u
                }
                // Form the gradient from original residuals, avoiding the
                // cancellation of K*u + g along weak LF directions.
                guard let current = objective(u, μ) else { break newton }
                gemv(m, small, 2, M, m, .T, trialResidual, 1, 0, &dataGradient, 1)
                for c in 0..<N { gradient[c] = factor[c] * dataGradient[κ[c]] }
                for c in 0..<N {
                    let W = c < nP ? Wp : Wq
                    let d = c < nP ? p : q
                    gradient[c] -= μ * factor[c] * W[row[c] + col[c] * d]
                }
                for c2 in 0..<N {
                    let W = c2 < nP ? Wp : Wq
                    let d = c2 < nP ? p : q
                    let lower = c2 < nP ? 0 : nP
                    let upper = c2 < nP ? nP : N
                    let (i2, j2) = (row[c2], col[c2])
                    for c1 in 0..<N {
                        H[c1 + c2 * N] = 2 * K[c1 + c2 * N]
                    }
                    for c1 in lower..<upper {
                        let (i1, j1) = (row[c1], col[c1])
                        let v = W[i1 + i2 * d] * W[j1 + j2 * d] + W[i1 + j2 * d] * W[j1 + i2 * d]
                        H[c1 + c2 * N] += μ * factor[c1] * factor[c2] * v / 2
                    }
                }
                // K₀ is rank-deficient, so PD rests on the barrier term; near
                // the cone boundary W ~ 1/ε inflates the dynamic range beyond
                // double rounding. Retry with Levenberg damping instead of dying.
                var HF = H
                var damping = 0.0
                var factorized = true
                while potrf(N, &HF, N, .L) != 0 {
                    var scale = 0.0
                    for c in 0..<N {
                        scale = max(scale, H[c + c * N])
                    }
                    damping = max(16 * damping, 0x1p-44 * scale)
                    guard damping.isFinite, damping < scale else {
                        factorized = false
                        break
                    }
                    for c2 in 0..<N {
                        for c1 in 0..<N {
                            HF[c1 + c2 * N] = H[c1 + c2 * N]
                        }
                        HF[c2 + c2 * N] += damping
                    }
                }
                guard factorized else {
                    break newton // Hessian numerically indefinite beyond repair at this μ
                }
                for c in 0..<N { // columns: -∇ and a (for the equality Schur step)
                    rhs[c] = -gradient[c]
                    rhs[N + c] = a[c]
                }
                switch potrs(N, 2, &HF, N, .L, &rhs, N) {
                case let info:
                    assert(info == 0)
                }
                let drift = β - dot(N, a, 1, u, 1)
                var ah = 0.0
                var ag = 0.0
                for c in 0..<N {
                    ah += a[c] * rhs[N + c]
                    ag += a[c] * rhs[c]
                }
                let ν = (ag - drift) / ah
                var decrement = 0.0
                for c in 0..<N {
                    rhs[c] -= ν * rhs[N + c]
                    decrement -= gradient[c] * rhs[c]
                }
                guard decrement.isFinite, decrement >= 0 else { break newton }
                if decrement <= max(1e-28 * scaleK, 1e-6 * μ) { break newton }
                // Armijo descent as well as cone feasibility is required.
                var t = 1.0
                var accepted = false
                while 0x1p-52 < t {
                    for c in 0..<N {
                        candidate[c] = u[c] + t * rhs[c]
                    }
                    if let value = objective(candidate, μ),
                       value <= current - 0.01 * t * decrement {
                        accepted = true
                        break
                    }
                    t /= 2
                }
                guard accepted else {
                    break newton // boundary-pinned; keep the last interior iterate
                }
                swap(&u, &candidate)

            }
            if μ <= μfloor {
                break
            }
            μ = max(0.05 * μ, μfloor)
        }
        // Coefficients from the strictly feasible iterate; the common rescale
        // restores p₀ + q₀ = 2 exactly without changing P/Q.
        var coefficients = Array<Float64>(repeating: 0, count: small)
        coefficients[0] = ε
        coefficients[p] = ε
        for c in 0..<N {
            coefficients[κ[c]] += factor[c] * u[c]
        }
        let scale = 2 / (coefficients[0] + coefficients[p])
        vDSP.multiply(scale, coefficients, result: &coefficients)
        return .init(raw: (Array(coefficients.prefix(p)),
                           Array(coefficients.suffix(q))))
    }
}
