//
//  Linear+WithClaude.swift
//  MUTE
//  NOTE: This codebase is generated by Claude (Fable 5)
//  Globally optimal positive power fitting via Riesz–Fejér Gram lifting.
//

import protocol Accelerate.AccelerateBuffer
import typealias Accelerate.vDSP
import typealias Accelerate.vForce
import BLAS
import LAPACK

extension Linear {
    /// Alternative power fitter kept in a namespace so it can coexist with
    /// `Linear.fit(xx:yy:frequency:weight:iteration:minimum:count:)`.
    public enum WithClaude {}
}

extension Linear.WithClaude {
    /// Fits `P(cos 2πω) Sxx - Q(cos 2πω) Syy = 0` with `P, Q >= minimum` on
    /// the whole interval, to global optimality.
    ///
    /// Because the Chebyshev argument is `cos 2πω`, interval nonnegativity is
    /// circle nonnegativity of an even trigonometric polynomial, so
    /// Riesz–Fejér applies exactly: `P - ε = ψᴴ G ψ` with one PSD Gram matrix
    /// `G` per polynomial and the linear map `p₀ = ε + tr G`,
    /// `p_k = 2 Σᵢ G[i, i+k]`. The semi-infinite constraint becomes two small
    /// PSD cones — no grid constraints, no cutting planes, no barrier bias —
    /// and the whole problem is a convex semidefinite least squares whose
    /// solution is the global optimum of the original fit.
    ///
    /// The cone program is solved by a primal log-det barrier with damped
    /// Newton steps (`potrf`/`potrs`); affine invariance keeps the
    /// band-edge-compressed directions of the Chebyshev basis from slowing
    /// convergence, and backtracking on the Cholesky feasibility check keeps
    /// every iterate strictly inside the cones.
    public static func fit(xx x: some AccelerateBuffer<Float64>,
                           yy y: some AccelerateBuffer<Float64>,
                           frequency ω: some AccelerateBuffer<Float64>, // normalized angular frequency, [0, 0.5] a.k.a. [0, π] or [0, 1) a.k.a. [0, 2π)
                           weight w: some AccelerateBuffer<Float64>, // weight factor for each frequency ω
                           iteration: Optional<Int> = .none,
                           minimum ε: Float64,
                           count: (p: Int, q: Int)) -> Linear.Direct.Power {
        let m = ω.count
        precondition(0 < m)
        precondition(m == x.count)
        precondition(m == y.count)
        precondition(m == w.count)
        precondition(0 <= count.p)
        precondition(0 <= count.q)
        precondition(ε.isFinite && 0 < ε && ε < 1)
        precondition(x.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        precondition(y.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        precondition(ω.withUnsafeBufferPointer { $0.allSatisfy(\.isFinite) })
        precondition(w.withUnsafeBufferPointer { $0.allSatisfy { $0.isFinite && 0 <= $0 } })
        let p = count.p + 1
        let q = count.q + 1
        let small = p + q
        let root2 = 2.0.squareRoot()
        let xx = x.withUnsafeBufferPointer(Array.init)
        let yy = y.withUnsafeBufferPointer(Array.init)
        let ww = w.withUnsafeBufferPointer(Array.init)
        let ff = ω.withUnsafeBufferPointer(Array.init)
        // Weighted data columns: base[l] = sqrt(w/(x² + y²)) (x, -y).
        var xcol = Array<Float64>(repeating: 0, count: m)
        var ycol = Array<Float64>(repeating: 0, count: m)
        for (l, h) in vDSP.hypot(xx, yy).enumerated() {
            let s = ww[l].squareRoot()
            if 0 < h, h.isFinite, 0 < s {
                xcol[l] =  s * xx[l] / h
                ycol[l] = -s * yy[l] / h
            }
        }
        // M[:, k] = xcol T_k, M[:, p + k] = ycol T_k; T_k(cos 2πω) = cos 2πkω.
        var M = Array<Float64>(repeating: 0, count: m * small)
        M.replaceSubrange(0..<m, with: xcol)
        M.replaceSubrange(p * m ..< p * m + m, with: ycol)
        if 1 < max(p, q) {
            var t = Array<Float64>(repeating: 0, count: m)
            for k in 1..<max(p, q) {
                vDSP.multiply(2 * Float64(k), ff, result: &t)
                vForce.cosPi(t, result: &t)
                if k < p {
                    vDSP.multiply(t, xcol, result: &M[k * m ..< k * m + m])
                }
                if k < q {
                    vDSP.multiply(t, ycol, result: &M[(p + k) * m ..< (p + k) * m + m])
                }
            }
        }
        // Small data Gram; every lifted column is a scaled copy of a column
        // of M, so the big quadratic expands from Γ without materializing it.
        var Γ = Array<Float64>(repeating: 0, count: small * small)
        gemm(small, small, m, 1, M, m, .T, M, m, .N, 0, &Γ, small)
        // Scaled svec layout (‖svec‖₂ = ‖G‖_F): per block, columns j, rows
        // i <= j; the entry feeds Chebyshev coefficient k = j - i of its
        // polynomial with factor 1 on the diagonal and √2 off it.
        let nP = p * (p + 1) / 2
        let nQ = q * (q + 1) / 2
        let N = nP + nQ
        var κ = Array<Int>()     // column of M the svec entry couples to
        var factor = Array<Float64>()
        var diagonal = Array<Bool>()
        var row = Array<Int>()
        var col = Array<Int>()
        κ.reserveCapacity(N)
        factor.reserveCapacity(N)
        diagonal.reserveCapacity(N)
        row.reserveCapacity(N)
        col.reserveCapacity(N)
        for (base, d) in [(0, p), (p, q)] {
            for j in 0..<d {
                for i in 0...j {
                    κ.append(base + j - i)
                    factor.append(i == j ? 1 : root2)
                    diagonal.append(i == j)
                    row.append(i)
                    col.append(j)
                }
            }
        }
        // K₀ = ÂᵀÂ with Â = M L, L the svec→coefficient map; objective uᵀK₀u + 2gᵀu.
        var K = Array<Float64>(repeating: 0, count: N * N)
        for c2 in 0..<N {
            for c1 in 0..<N {
                K[c1 + c2 * N] = factor[c1] * factor[c2] * Γ[κ[c1] + κ[c2] * small]
            }
        }
        // Linear term of ‖Âu + b‖²: b = ε (M[:,0] + M[:,p]) from the constant
        // Chebyshev coefficients of both polynomials.
        var g = Array<Float64>(repeating: 0, count: N)
        for c in 0..<N {
            g[c] = ε * factor[c] * (Γ[κ[c] + 0 * small] + Γ[κ[c] + p * small])
        }
        // Equality p₀ + q₀ = 2 ⟺ tr G + tr H = 2 - 2ε.
        let β = 2 - 2 * ε
        var a = Array<Float64>(repeating: 0, count: N)
        for c in 0..<N where diagonal[c] {
            a[c] = 1
        }
        // svec ↔ dense block helpers
        let dmax = max(p, q)
        var S = Array<Float64>(repeating: 0, count: dmax * dmax)
        var Wp = Array<Float64>(repeating: 0, count: p * p)
        var Wq = Array<Float64>(repeating: 0, count: q * q)
        func dense(_ u: borrowing Array<Float64>, _ offset: Int, _ d: Int) {
            var c = offset
            for j in 0..<d {
                for i in 0...j {
                    let value = i == j ? u[c] : u[c] / root2
                    S[i + j * d] = value
                    S[j + i * d] = value
                    c += 1
                }
            }
        }
        func feasible(_ u: borrowing Array<Float64>) -> Bool {
            for (offset, d) in [(0, p), (nP, q)] {
                dense(u, offset, d)
                guard potrf(d, &S, d, .L) == 0 else { return false }
            }
            return true
        }
        // W ← block⁻¹ via Cholesky; returns log det or nil when not PD
        func invert(_ u: borrowing Array<Float64>, _ offset: Int, _ d: Int, _ W: inout Array<Float64>) -> Bool {
            dense(u, offset, d)
            guard potrf(d, &S, d, .L) == 0 else { return false }
            W.withUnsafeMutableBufferPointer {
                vDSP.clear(&$0[...])
                for i in 0..<d {
                    $0[i + i * d] = 1
                }
            }
            switch potrs(d, d, &S, d, .L, &W, d) {
            case let info:
                assert(info == 0)
                return true
            }
        }
        // Primal log-det barrier with damped Newton: affine invariant, so the
        // near-singular band-edge directions of K₀ do not slow convergence.
        var u = Array<Float64>(repeating: 0, count: N)
        for c in 0..<N where diagonal[c] { // strictly feasible start: P = Q = 1
            u[c] = (1 - ε) / Float64(c < nP ? p : q)
        }
        var gradient = Array<Float64>(repeating: 0, count: N)
        var H = Array<Float64>(repeating: 0, count: N * N)
        var rhs = Array<Float64>(repeating: 0, count: 2 * N)
        var candidate = u
        let scaleK = (0..<N).reduce(0.0) { $0 + K[$1 + $1 * N] } / Float64(N)
        let μfloor = 1e-14 * max(scaleK, 1)
        var μ = max(scaleK, 1)
        while true {
            for _ in 0..<(iteration ?? 64) {
                guard invert(u, 0, p, &Wp), invert(u, nP, q, &Wq) else {
                    preconditionFailure("infeasible iterate")
                }
                // ∇ = 2(K₀u + g) - μ svec(W), ∇² = 2K₀ + μ (W ⊗ₛ W)
                gemv(N, N, 2, K, N, .N, u, 1, 0, &gradient, 1)
                for c in 0..<N {
                    let W = c < nP ? Wp : Wq
                    let d = c < nP ? p : q
                    gradient[c] += 2 * g[c] - μ * factor[c] * W[row[c] + col[c] * d]
                }
                for c2 in 0..<N {
                    let W = c2 < nP ? Wp : Wq
                    let d = c2 < nP ? p : q
                    let lower = c2 < nP ? 0 : nP
                    let upper = c2 < nP ? nP : N
                    let (i2, j2) = (row[c2], col[c2])
                    for c1 in 0..<N {
                        H[c1 + c2 * N] = 2 * K[c1 + c2 * N]
                    }
                    for c1 in lower..<upper {
                        let (i1, j1) = (row[c1], col[c1])
                        let v = W[i1 + i2 * d] * W[j1 + j2 * d] + W[i1 + j2 * d] * W[j1 + i2 * d]
                        H[c1 + c2 * N] += μ * factor[c1] * factor[c2] * v / 2
                    }
                }
                switch potrf(N, &H, N, .L) {
                case let info:
                    precondition(info == 0) // barrier Hessian is PD on the feasible set
                }
                for c in 0..<N { // columns: -∇ and a (for the equality Schur step)
                    rhs[c] = -gradient[c]
                    rhs[N + c] = a[c]
                }
                switch potrs(N, 2, &H, N, .L, &rhs, N) {
                case let info:
                    assert(info == 0)
                }
                let drift = β - dot(N, a, 1, u, 1)
                var ah = 0.0
                var ag = 0.0
                for c in 0..<N {
                    ah += a[c] * rhs[N + c]
                    ag += a[c] * rhs[c]
                }
                let ν = (ag - drift) / ah
                var decrement = 0.0
                for c in 0..<N {
                    rhs[c] -= ν * rhs[N + c]
                    decrement -= gradient[c] * rhs[c]
                }
                // backtrack to stay inside the PSD cones
                var t = 1.0
                while 0x1p-52 < t {
                    for c in 0..<N {
                        candidate[c] = u[c] + t * rhs[c]
                    }
                    if feasible(candidate) {
                        break
                    }
                    t /= 2
                }
                swap(&u, &candidate)
                if abs(decrement) <= 1e-12 * (1 + μ) {
                    break
                }
            }
            if μ <= μfloor {
                break
            }
            μ = max(0.05 * μ, 0.999 * μfloor)
        }
        // Coefficients from the strictly feasible iterate; the common rescale
        // restores p₀ + q₀ = 2 exactly without changing P/Q.
        var coefficients = Array<Float64>(repeating: 0, count: small)
        coefficients[0] = ε
        coefficients[p] = ε
        for c in 0..<N {
            coefficients[κ[c]] += factor[c] * u[c]
        }
        let scale = 2 / (coefficients[0] + coefficients[p])
        vDSP.multiply(scale, coefficients, result: &coefficients)
        return .init(raw: (Array(coefficients.prefix(p)),
                           Array(coefficients.suffix(q))))
    }
}
